rules:
  - description: AWS Access Key ID
    regex: (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
    tags:
      - AWS
      - Credential
  - description: AWS Secret Access Key
    regex: (?i)aws_secret_access_key|aws_access_key_id|AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID\s*=\s*[a-zA-Z0-9/\+]{40}
    tags:
      - AWS
      - Credential
  - description: Generic API Key
    regex: (?i)(api_key|api-key|apikey|api-token|api_token)\s*=\s*['\"][a-z0-9_\-]{16,64}['\"]
    tags:
      - API Key
  - description: Private Key
    regex: |(?i)BEGIN[ -](?:RSA|DSA|EC|PGP) PRIVATE KEY[ -]|ssh-rsa\s*[a-z0-9\+\/]{100,}
    tags:
      - Private Key
  - description: Generic Password
    regex: (?i)(password|passphrase|pwd)\s*[:=]\s*['\"]([^\s']{8,64})['\"]
    tags:
      - Password
